//
//  ViewController.swift
//  FCM Notification Tester
//
//  Created by Vinicius Soares on 09/07/21.
//

import UIKit
import Firebase

class ViewController: UIViewController, UITextViewDelegate, MessagingDelegate {
    var deviceID: String = ""
    var fcmToken: String = "Loading..."
    
    /**
        Uses non-editable UITextView instead of UITextLabel so the user can easily select and
        copy its value to register the token and - if needed - the ID on the Firebase to test the
        push notifications trigger.
     */
    @IBOutlet weak var deviceIDValue: UITextView!
    @IBOutlet weak var fcmTokenValue: UITextView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.deviceIDValue.delegate = self
        self.fcmTokenValue.delegate = self
        
        /**
         Associates this class to handle the events triggered by the Messaging class so the View
         Controller can handle the token generated by the FCM library.
         */
        Messaging.messaging().delegate = self
        
        self.deviceID = UIDevice.current.identifierForVendor!.uuidString
        self.deviceIDValue.text = self.deviceID
        
        self.fcmTokenValue.text = self.fcmToken
    }
    
    /**
        Listens to the "didReceiveRegistrationToken" event so the class can get the token and handle
        it to show its value on the screen.
     */
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        print("Firebase token: \(fcmToken ?? "")")
      
        self.fcmToken = fcmToken ?? "Loading..."
        self.fcmTokenValue.text = self.fcmToken
    }
}

