# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FCM Notification Tester' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for FCM Notification Tester

  pod 'Firebase/Analytics'

  pod 'Firebase/Messaging' 

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
